### ISSUE TITLE
Floating Point Errors

### ISSUE THREAD

**Issue by hans20253** [hans20253/repository#4]
Getting floating point errors. An example would be we get 0.73605 and -0.73605 and their sum is not zero, since they end up having more precision than displayed, so the answer comes to roughly ~10^-16.

**Comment by AetherUnbound** [comment]
Would it be possible to just include a conditional statement to round to zero if it's that small?

**Comment by hans20253** [comment]
what I did for now was take the minimum x coordinate of the input, and then since the dot product is at most quadratic in x, since we could have x^2+y^2+z^2. So If  0<abs(dotproduct)<min^4, then the dot product is 0
